### ISSUE TITLE
Fix Flutter Logo in Markdown

### ISSUE THREAD

**Issue by KFChinese** [KFChinese/The-Year-Up-Applcation#1]
Link is currently broken.

**Comment by Abhijeet-sonkar** [comment]
Can I work on this issue?

**Comment by KFChinese** [comment]
Hi @Abhijeet-sonkar! 
Thank you for requesting to work on this issue, but sadly, this repository will become deprecated and read only, as this project has not came to fruition with the original intent for Year Up students.  
I hope that you find other projects that you would like to work on or something that I would work on from you and again, 
Thank you!
-Larry
